baseURL = "/"
languageCode = "en-us"
title = "Teleskop w ILO"
description = "Kronika dziejów obserwatorium w I Liceum Ogólnokształcącym im. Mikołaja Kopernika, i sprzętom z nim związanym"
author = "Norbert Szulc"
canonifyurls = true
languagecode = "pl"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Teleskop w ILO"

[[menu.main]]
    name = "Galeria"
    url  = "galeria"
    weight = 10

[[menu.main]]
    name = "Kolofon"
    url  = "kolofon"
    weight = 0