baseURL = "/"
languageCode = "en-us"
title = "Teleskop w ILO"
author = "Norbert Szulc"
canonifyurls = true
languagecode = "pl"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Teleskop w ILO"

[[menu.main]]
    name = "Kontakt"
    url  = "kontakt"
    weight = 10

[[menu.main]]
    name = "Kolofon"
    url  = "kolofon"
    weight = 0